version: 2

dependencies:
  override:
    - yarn

jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run:
          name: "Install `Now`"
          command: yarn global add now 
      - run:
          name: "Deploy to Now"
          command: now -t qlCKyiruBgEDfJ2Ir2zCvpjV