version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run:
          name: "Install Now CLI"
          command: sudo npm i -g --unsafe-perm now
      - run:
          name: "Install dependencies"
          command: npm i
      - run:
          name: "Build"
          command: npm run build
      - run:
          name: "Login to Now"
          command: now -t jCz2V3dlQjLuCEdM2HvlZoEk