version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - deploy:
          name: "Deploy"
          environment:
            NOW_TOKEN: jCz2V3dlQjLuCEdM2HvlZoEk
          commands:
            - run:
                name: "Install Now CLI"
                command: sudo npm i -g --unsafe-perm now
            - run:
                name: "Deploy to Now"
                command: now -t NOW_TOKEN
            - run:
                name: "Now alias"
                command: now -t $NOW_TOKEN ln
      # end