version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run:
          name: "Install Now CLI"
          command: sudo npm i -g --unsafe-perm now
      - run:
          name: "Deploy to Now"
          command: now -t jCz2V3dlQjLuCEdM2HvlZoEk
      - run:
          name: "Now alias"
          command: now -t jCz2V3dlQjLuCEdM2HvlZoEk ln